#!/bin/bash

# Customize this for your application


# Parameters
PRODUCT_HOME=/usr/local/ghc

echo "Post installation process started"

${PRODUCT_HOME}/configure
${PRODUCT_HOME}/make install

# Change permissions in home directory
# echo "Change permissions in product home"
# cd ${PRODUCT_HOME}
# chmod -R 755 .
# [ -d /usr/local/bin ] || mkdir /usr/local/bin

# Add application shortcut to /usr/local/bin
# rm -f /usr/local/bin/__PRODUCT__-__VERSION__
# ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/__PRODUCT__-__VERSION__
echo "Post installation process finished"
